FROM postgres:15

RUN apt-get update && apt-get install -y gettext && rm -rf /var/lib/apt/lists/*

COPY docker-config/ /docker-entrypoint-initdb.d/

ENTRYPOINT ["/docker-entrypoint-initdb.d/entrypoint.sh"]
