"""Add cascade delete on Inquiry

Revision ID: 0942fe9ee741
Revises: 5c3851680185
Create Date: 2024-10-31 12:47:20.847419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0942fe9ee741'
down_revision: Union[str, None] = '5c3851680185'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('message_inquiry_id_fkey', 'message', type_='foreignkey')
    op.create_foreign_key(None, 'message', 'inquiry', ['inquiry_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'message', type_='foreignkey')
    op.create_foreign_key('message_inquiry_id_fkey', 'message', 'inquiry', ['inquiry_id'], ['id'])
    # ### end Alembic commands ###
