"""added table inquiry_message_mapping

Revision ID: 12b7a1b09791
Revises: 6fa910846c2e
Create Date: 2024-10-23 00:04:13.889735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12b7a1b09791'
down_revision: Union[str, None] = '6fa910846c2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inquiry_message_mapping',
    sa.Column('inquiry_id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.BigInteger(), nullable=False),
    sa.Column('subdivision_thread_id', sa.BigInteger(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['inquiry_id'], ['inquiry.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subdivision_thread_id'], ['subdivision_message_thread.message_thread_id'], ),
    sa.PrimaryKeyConstraint('inquiry_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inquiry_message_mapping')
    # ### end Alembic commands ###
