"""added employee.password nullable=true

Revision ID: 31c05b18925c
Revises: 66c25d24f687
Create Date: 2024-10-11 11:21:35.718440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31c05b18925c'
down_revision: Union[str, None] = '66c25d24f687'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee', sa.Column('password', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employee', 'password')
    # ### end Alembic commands ###
