"""restructuring Subdivision... move out gsheet_id to new table subdivision_gsheet

Revision ID: 4867173c022e
Revises: 12b7a1b09791
Create Date: 2024-10-23 11:09:13.037606

"""
from typing import Sequence, Union

from alembic import op
from sqlalchemy import text
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4867173c022e'
down_revision: Union[str, None] = '12b7a1b09791'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subdivision_gsheet',
    sa.Column('subdivision_id', sa.Integer(), nullable=False),
    sa.Column('gsheets_id', sa.String(length=255), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['subdivision_id'], ['subdivision.id'], ),
    sa.PrimaryKeyConstraint('subdivision_id'),
    sa.UniqueConstraint('gsheets_id')
    )
    op.drop_constraint('subdivision_gsheets_id_key', 'subdivision', type_='unique')



    conn = op.get_bind()
    conn.execute(text("""
            INSERT INTO subdivision_gsheet (gsheets_id, subdivision_id, created, updated)
            SELECT gsheets_id, id, now(), now() FROM subdivision
        """))



    op.drop_column('subdivision', 'gsheets_id')
    # ### end Alembic commands ###



def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subdivision', sa.Column('gsheets_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.create_unique_constraint('subdivision_gsheets_id_key', 'subdivision', ['gsheets_id'])

    conn = op.get_bind()
    conn.execute(text("""
            UPDATE subdivision
            SET gsheets_id = (
                SELECT gsheets_id FROM subdivision_gsheet
                WHERE subdivision_gsheet.subdivision_id = subdivision.id
            )
        """))


    op.drop_table('subdivision_gsheet')
    # ### end Alembic commands ###
