"""Add cascade delete on Subdivision foreign keys

Revision ID: 5c3851680185
Revises: 08f61ffd1838
Create Date: 2024-10-31 12:41:53.726168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c3851680185'
down_revision: Union[str, None] = '08f61ffd1838'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('inquiry_subdivision_id_fkey', 'inquiry', type_='foreignkey')
    op.create_foreign_key(None, 'inquiry', 'subdivision', ['subdivision_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('subdivision_gsheet_subdivision_id_fkey', 'subdivision_gsheet', type_='foreignkey')
    op.create_foreign_key(None, 'subdivision_gsheet', 'subdivision', ['subdivision_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('subdivision_message_thread_subdivision_id_fkey', 'subdivision_message_thread', type_='foreignkey')
    op.create_foreign_key(None, 'subdivision_message_thread', 'subdivision', ['subdivision_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('time_record_subdivision_id_fkey', 'time_record', type_='foreignkey')
    op.create_foreign_key(None, 'time_record', 'subdivision', ['subdivision_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'time_record', type_='foreignkey')
    op.create_foreign_key('time_record_subdivision_id_fkey', 'time_record', 'subdivision', ['subdivision_id'], ['id'])
    op.drop_constraint(None, 'subdivision_message_thread', type_='foreignkey')
    op.create_foreign_key('subdivision_message_thread_subdivision_id_fkey', 'subdivision_message_thread', 'subdivision', ['subdivision_id'], ['id'])
    op.drop_constraint(None, 'subdivision_gsheet', type_='foreignkey')
    op.create_foreign_key('subdivision_gsheet_subdivision_id_fkey', 'subdivision_gsheet', 'subdivision', ['subdivision_id'], ['id'])
    op.drop_constraint(None, 'inquiry', type_='foreignkey')
    op.create_foreign_key('inquiry_subdivision_id_fkey', 'inquiry', 'subdivision', ['subdivision_id'], ['id'])
    # ### end Alembic commands ###
