"""renamed inquiry_message_mapping.subdivision_thread_id to message_thread_id

Revision ID: 6dc261292c44
Revises: 69fca242e4ca
Create Date: 2024-10-23 17:27:57.440819

"""
from typing import Sequence, Union

from sqlalchemy import text
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6dc261292c44'
down_revision: Union[str, None] = '69fca242e4ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inquiry_message_mapping', sa.Column('message_thread_id', sa.BigInteger(), nullable=True))


    # manually added
    op.execute(text("""
            UPDATE inquiry_message_mapping 
            SET message_thread_id = subdivision_thread_id
        """))

    op.alter_column('inquiry_message_mapping', 'message_thread_id', nullable=False)
    # EOF manually added

    op.drop_constraint('inquiry_message_mapping_subdivision_thread_id_fkey', 'inquiry_message_mapping', type_='foreignkey')
    op.create_foreign_key(None, 'inquiry_message_mapping', 'subdivision_message_thread', ['message_thread_id'], ['message_thread_id'])
    op.drop_column('inquiry_message_mapping', 'subdivision_thread_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inquiry_message_mapping', sa.Column('subdivision_thread_id', sa.BIGINT(), autoincrement=False, nullable=True))

    # manually added
    op.execute(text("""
            UPDATE inquiry_message_mapping 
            SET subdivision_thread_id = message_thread_id
        """))

    op.alter_column('inquiry_message_mapping', 'subdivision_thread_id', nullable=False)
    # EOF manually added

    op.drop_constraint(None, 'inquiry_message_mapping', type_='foreignkey')
    op.create_foreign_key('inquiry_message_mapping_subdivision_thread_id_fkey', 'inquiry_message_mapping', 'subdivision_message_thread', ['subdivision_thread_id'], ['message_thread_id'])
    op.drop_column('inquiry_message_mapping', 'message_thread_id')
    # ### end Alembic commands ###
