"""added message_thread_id unique=True

Revision ID: 6fa910846c2e
Revises: 25d488f8026e
Create Date: 2024-10-23 00:03:29.624955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fa910846c2e'
down_revision: Union[str, None] = '25d488f8026e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'subdivision_message_thread', ['message_thread_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subdivision_message_thread', type_='unique')
    # ### end Alembic commands ###
