"""added subdivision.gsheets_id nullable=true

Revision ID: 7678ca6b08aa
Revises: 8b6a0efcb960
Create Date: 2024-10-11 16:27:03.302945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7678ca6b08aa'
down_revision: Union[str, None] = '8b6a0efcb960'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subdivision', sa.Column('gsheets_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subdivision', 'gsheets_id')
    # ### end Alembic commands ###
