"""added subdivision.gsheets_id unique=true,nullable=false

Revision ID: 7bfcfe3616e0
Revises: 7678ca6b08aa
Create Date: 2024-10-11 17:10:01.030131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7bfcfe3616e0'
down_revision: Union[str, None] = '7678ca6b08aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subdivision', 'gsheets_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.create_unique_constraint(None, 'subdivision', ['gsheets_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subdivision', type_='unique')
    op.alter_column('subdivision', 'gsheets_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###
