"""added inquiry.subdivision_id

Revision ID: 8afd0532ca61
Revises: 6dc261292c44
Create Date: 2024-10-23 17:45:28.182376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8afd0532ca61'
down_revision: Union[str, None] = '6dc261292c44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inquiry', sa.Column('subdivision_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'inquiry', 'subdivision', ['subdivision_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'inquiry', type_='foreignkey')
    op.drop_column('inquiry', 'subdivision_id')
    # ### end Alembic commands ###
