"""user -id -user_id +bot_id +user_id +chat_id all primary keys

Revision ID: 9c427f8572da
Revises: 4a111b67aa18
Create Date: 2024-10-16 13:32:13.552066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c427f8572da'
down_revision: Union[str, None] = '4a111b67aa18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bot_id', sa.BigInteger(), nullable=False))
    op.add_column('users', sa.Column('chat_id', sa.BigInteger(), nullable=False))
    op.drop_constraint('users_user_id_key', 'users', type_='unique')
    op.drop_column('users', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.create_unique_constraint('users_user_id_key', 'users', ['user_id'])
    op.drop_column('users', 'chat_id')
    op.drop_column('users', 'bot_id')
    # ### end Alembic commands ###
