"""main tables

Revision ID: ab2caa1b795f
Revises: 05c9773cec45
Create Date: 2024-10-21 15:46:35.792285

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab2caa1b795f'
down_revision: Union[str, None] = '05c9773cec45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tab_no', sa.String(length=16), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('pin', sa.String(length=6), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pin'),
    sa.UniqueConstraint('tab_no')
    )
    op.create_table('subdivision',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gsheets_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gsheets_id')
    )
    op.create_table('users',
    sa.Column('bot_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('fsm_state', sa.Text(), nullable=True),
    sa.Column('fsm_data', sa.JSON(), nullable=True),
    sa.Column('locale', sa.String(length=2), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('bot_id', 'user_id', 'chat_id'),
    sa.UniqueConstraint('bot_id', 'user_id', 'chat_id', name='users_unique_constraint')
    )
    op.create_table('time_record',
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('subdivision_id', sa.Integer(), nullable=False),
    sa.Column('work_date', sa.Date(), nullable=False),
    sa.Column('hours_worked', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.CheckConstraint('hours_worked >= 0', name='hours_worked >= 0'),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ),
    sa.ForeignKeyConstraint(['subdivision_id'], ['subdivision.id'], ),
    sa.PrimaryKeyConstraint('employee_id', 'subdivision_id', 'work_date')
    )
    op.create_index('idx_time_records_employee_date', 'time_record', ['employee_id', 'work_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_time_records_employee_date', table_name='time_record')
    op.drop_table('time_record')
    op.drop_table('users')
    op.drop_table('subdivision')
    op.drop_table('employee')
    # ### end Alembic commands ###
