"""employee.pin and employee.password

Revision ID: aca3f3533d05
Revises: 87a9b914c6f3
Create Date: 2024-10-15 14:22:23.603492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aca3f3533d05'
down_revision: Union[str, None] = '87a9b914c6f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee', sa.Column('pin', sa.String(length=6), nullable=False))
    op.alter_column('employee', 'password',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_constraint('employee_password_key', 'employee', type_='unique')
    op.create_unique_constraint(None, 'employee', ['pin'])
    op.drop_column('employee', 'is_password_changed')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee', sa.Column('is_password_changed', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'employee', type_='unique')
    op.create_unique_constraint('employee_password_key', 'employee', ['password'])
    op.alter_column('employee', 'password',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('employee', 'pin')
    # ### end Alembic commands ###
