"""Add unique constraint to bot_id, user_id, chat_id

Revision ID: f25bf478bc01
Revises: 9c427f8572da
Create Date: 2024-10-16 14:13:48.367297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f25bf478bc01'
down_revision: Union[str, None] = '9c427f8572da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('users_unique_constraint', 'users', ['bot_id', 'user_id', 'chat_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_unique_constraint', 'users', type_='unique')
    # ### end Alembic commands ###
